/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.51
 * Generated at: 2018-08-28 02:22:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head lang=\"en\">\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>商城用户登录</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/base.css\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/login.css\"/>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"main\">\r\n");
      out.write("    <div id=\"header\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"bgPic\"><img src=\"img/register/b3_1.jpg\" alt=\"\"/></div>\r\n");
      out.write("        <div class=\"register\">\r\n");
      out.write("            <div class=\"title\">\r\n");
      out.write("                <span>登录</span>\r\n");
      out.write("                <a href=\"register.jsp\">去注册</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <form action=\"login.do\" autocomplete=\"off\">\r\n");
      out.write("            \r\n");
      out.write("                <div class=\"default\">\r\n");
      out.write("                    <p>请输入用户名或手机号码</p>\r\n");
      out.write("                    <input id=\"uname\" name=\"uname\" data-form=\"required:true\" type=\"text\" placeholder=\"用户名\"  autofocus required />\r\n");
      out.write("                   <!--  <label for=\"uname\"></label> -->\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"default\">\r\n");
      out.write("                    <p>请输入账号密码</p>\r\n");
      out.write("                    <input id=\"upwd\" name=\"upass\" data-form=\"required:true\" type=\"password\" placeholder=\"密码\"  autofocus required/>\r\n");
      out.write("                    <!-- <label for=\"upwd\"></label> -->\r\n");
      out.write("                </div>\r\n");
      out.write("              \r\n");
      out.write("\t\t\t\t<div class=\"default\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"vcode\" required placeholder=\"请输入下面的验证码\" />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<img alt=\"无图片\" src=\"http://localhost/xiezi44/vc.do\" height=\"40px\"\r\n");
      out.write("\t\t\t\t\t\tonclick=\"src='http://localhost/xiezi44/vc.do?'+new Date();\">\r\n");
      out.write("                <div class=\"submit\">\r\n");
      out.write("                        <span class=\"notice\">\r\n");
      out.write("                            <a href=\"#\">忘记密码</a>\r\n");
      out.write("                        </span>\r\n");
      out.write("                        ");
if(request.getAttribute("msg")!=null){ 
      out.write("\r\n");
      out.write("                        <a >");
      out.print(request.getAttribute("msg") );
      out.write("</a>\r\n");
      out.write("                        ");
} 
      out.write("\r\n");
      out.write("                    <button class=\"s_hover\" data-form=\"submit\">登录</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("            <div class=\"other_login\">\r\n");
      out.write("                <div class=\"log\">\r\n");
      out.write("                    <span>社交账号登录</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"icon\">\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li data-log=\"icon\" class=\"i_hover\">\r\n");
      out.write("                            <img data-icon=\"wx\" src=\"img/register/wx.png\" alt=\"\"/>\r\n");
      out.write("                            <span class=\"prompt\" >微信登录</span>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li data-log=\"icon\" class=\"i_hover\">\r\n");
      out.write("                            <img data-icon=\"qq\" src=\"img/register/qq.png\" alt=\"\"/>\r\n");
      out.write("                            <span class=\"prompt\" >QQ登录</span>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li data-log=\"icon\" class=\"i_hover\">\r\n");
      out.write("                            <img data-icon=\"wb\" src=\"img/register/wb.png\" alt=\"\"/>\r\n");
      out.write("                            <span class=\"prompt\" >微博登录</span>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"footer\">\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<script src=\"js/jquery-3.2.1.js\"></script>\r\n");
      out.write("<script src=\"js/header.js\"></script>\r\n");
      out.write("<script src=\"js/login.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
